version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5433:5433
  server:
    image: '2work:server'
    ports:
      - "8000:3000"
    depends_on:
      - postgres